version: '3.9'

services:
  redis-server:
    image: 'redis'
    ports:
      - "6379:6379"
  server:
    build: .
    ports:
      - '5555:5555'
  db:
    image: 'postgres'
    volumes:
      - hostDir:/var/lib/postgresql/data
volumes:
  hostDir: 