version: '3.9'

services:
  server:
    build: .
    ports:
      - '5555:5555'
  db:
    image: 'postgres'
    # ports:
    #   - '5432:5432'
    # environment:
    #   POSTGRES_PASSWORD: 'w2UIO@#bg532!'
    #   POSTGRES_USER: 'readonly'
    volumes:
      - hostDir:/var/lib/postgresql/data
volumes:
  hostDir: 